### ISSUE TITLE
Enhancement For  Control V-62265

### ISSUE THREAD

**Issue by samueleydaniel** [mitre/red-hat-jboss-eap-6.3-stig-baseline#11]
**Two Enhancement Proposed:**

1)  Add a new attribute for Jboss process name.(Ex: jboss_process_name)

2) Enhance the ps command like so
    ps -ef|grep -w #{ attribute('jboss_process_name')| grep -v inspec | grep -v grep | awk '{print $1}'|uniq

**Comment by aaronlippold** [comment]
Cool thanks. we should have this resolved soon
